import app.logger
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Table
import org.jetbrains.exposed.sql.transactions.TransactionManager
import org.jetbrains.exposed.sql.transactions.transaction
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.TestInstance
import java.util.logging.Logger
import kotlin.random.Random

/**
 * A test helper that creates an in-memory database for the lifetime of the test.
 *
 * @property databaseName The name of the temporary database. Randomly generated by default.
 * @property tables An array of tables to initialize. Will be dropped and created before each individual test.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
abstract class DatabaseForTest(
    private val databaseName: String = "test_db_${Random.nextInt(0, 9999)}",
    private val tables: Array<Table> = emptyArray(),
) {
    private val logger = Logger.getLogger("DatabaseForTest")

    @Suppress("MemberVisibilityCanBePrivate")
    protected val database = Database.connect("jdbc:h2:mem:$databaseName;DB_CLOSE_DELAY=-1;IGNORECASE=true;")

    @BeforeEach
    private fun databaseSetUp() {
        logger.info("Start in-memory DB for test")
        transaction (database) {
            SchemaUtils.drop(*tables)
            SchemaUtils.create(*tables)
        }
    }

    @AfterAll
    private fun databaseTearDown() {
        logger.info("Teardown in-memory DB for test")
        TransactionManager.closeAndUnregister(database)
    }

}
